# Generated by Django 2.1.7 on 2019-02-13 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('currency_form', models.CharField(max_length=128)),
                ('currency_to', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(default=datetime.date(2019, 2, 13))),
            ],
        ),
        migrations.CreateModel(
            name='RateWatched',
            fields=[
                ('rate_watched_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('currency_from', models.CharField(max_length=128)),
                ('currency_to', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='ratewatched',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_processor.User'),
        ),
    ]
