# Generated by Django 2.1.7 on 2019-02-13 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0004_auto_20190213_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
