# Generated by Django 2.1.7 on 2019-02-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0007_auto_20190213_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratewatched',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratewatched',
            name='rate_watched_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
