# Generated by Django 2.1.7 on 2019-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0010_auto_20190214_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
