# Generated by Django 2.1.7 on 2019-02-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0016_auto_20190217_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
