# Generated by Django 2.1.7 on 2019-02-17 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0017_auto_20190217_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
