# Generated by Django 2.1.7 on 2019-02-17 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_processor', '0018_auto_20190217_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
